### ISSUE TITLE
Visual Studio 2022 Support

### ISSUE THREAD

**Issue by WizX20** [sajalverma17/GitBranchDiffer#27]
### Installed product versions
* Visual Studio: 2022 All Versions

### Description
Make the extension available in Visual Studio 2022.

### Steps to recreate
1. Download the extension installer.
2. Run the installer.

### Current behavior
Message that it is already installed to all applicable products appears even though it is not installed in Visual Studio 2022. It is also not listed in Online Extensions in Manage Extensions Visual Studio 2022.

### Expected behavior
Installs and works in Visual Studio 2022.

_Note: Have a look at the [VS2022 CodeMaid Issue](https://github.com/codecadwallader/codemaid/issues/816) for some hints._

**Comment by sajalverma17** [comment]
Added support for VS2022 The PR is merged (with some Git history I messed up, just look at the last 13-ish commits which contain the actual upgrade work). 

As guided by Microsoft Extensibility team, we build two different VSIX installers, one for VS2019 and one for VS2022. The latest CI build now outputs both the VSIXs, and I have attached the ZIP output of CI Build Version 1.0.3.39 below. 

@WizX20 If you would like to, give the Alpha versions a test while I update the Publish workflow and create a new VS Marketplace Extension Page for VS2022 version of this plugin.
 
GitBranchDiffer.vsix - For VS2022 
GitBranchDiffer2019.vsix - For VS2019

[GitBranchDiffer-1.0.3.39.zip](https://github.com/sajalverma17/GitBranchDiffer/files/7577804/GitBranchDiffer-1.0.3.39.zip)

**Comment by WizX20** [comment]
Awesome! I will test the Alpha version the upcoming days and provide feedback.

**Comment by WizX20** [comment]
I've installed the VS2022 version on Microsoft Visual Studio Enterprise 2022 (64-bit) - Preview, Version 17.1.0 Preview 1.1
But I do not see the button/commands in the solution explorer or the context-menu.
- I can confirm the extension is installed via the Extensions Manager
- I can't seem to find the commands anywhere in VS

**Comment by sajalverma17** [comment]
@WizX20 Strange, I don't think it should have been possible to install `GitBranchDiffer.vsix` to Microsoft Visual Studio Enterprise at all.

GitBranchDiffer only supports Community and Professional variants of of Visual Studio 2022. I just didn't think of Enterprise variant at all when making this plugin. I have the below two variants of VS2022, and the given VSIX files worked on BOTH of the VS2022 variants.

1. Microsoft Visual Studio Community 2022 (64-bit) Version 17.1.0 Preview 1.1
2. Microsoft Visual Studio Professional 2022 (64-bit) Version 17.0.1

I unfortunately don't have the ability to test the Enterprise edition of VS, but it should be easy to add support for it.

**Comment by sajalverma17** [comment]
I added Visual Studio Enterprise edition as an Install Target for GitBranchDiffer2019 and 2022. So the plugin should now get installed to Visual Studio Community, Professional and Enterprise variants of both VS2019 and VS2022. 

Below are the VSIXs from the latest CI Build (Version 1.0.3.40) attached in a ZIP:

GitBranchDiffer.vsix - For VS2022
GitBranchDiffer2019.vsix - For VS2019
[GitBranchDiffer-1.0.3.40.zip](https://github.com/sajalverma17/GitBranchDiffer/files/7610819/GitBranchDiffer-1.0.3.40.zip)

@WizX20 If the issue was just that plugin didn't support Enterprise variants, this should solve it. If not, could you attach the Install Log that gets generated when installing the VSIXs?   

![image](https://user-images.githubusercontent.com/25904133/143658967-445d652e-739c-4785-b3b1-2557cf47d3e0.png)

**Comment by WizX20** [comment]
Hi, I installed the VS2022 version, but then I had two 😅 
So after that I removed both GitBranchDiffer v1.0.3.39 and GitBranchDiffer v1.0.3.42.

After that I installed GitBranchDiffer v1.0.3.42 again.

![image](https://user-images.githubusercontent.com/1008647/144463160-70f544bb-b34b-46db-b924-c82f11d1eae6.png)

[dd_VSIXInstaller_20211202172743_9a94.log](https://github.com/sajalverma17/GitBranchDiffer/files/7643506/dd_VSIXInstaller_20211202172743_9a94.log)

Starting Visual Studio gave me the following messages:
![image](https://user-images.githubusercontent.com/1008647/144565356-223814a8-fc23-43f8-b2e9-65c664fbedfc.png)
![image](https://user-images.githubusercontent.com/1008647/144565370-67230a36-1a8d-44cd-9f4f-96ac25aeb87c.png)
[ActivityLog.xml.txt](https://github.com/sajalverma17/GitBranchDiffer/files/7647689/ActivityLog.xml.txt)

Options are present:
![image](https://user-images.githubusercontent.com/1008647/144566565-90948a02-e0a3-417f-a562-578d248de638.png)

- Solution Explorer button is missing
- Context menu options are missing

**Comment by sajalverma17** [comment]
Hi @WizX20 
Thanks for the feedback. Sorry for a delay in my response, I am on a vacation for this whole month. 

First of all, I think you had both the versions installed at the same time because I changed the product ID of the plugin between the CI builds I gave you. Shouldn't be an issue now. 

Regarding the errors, I didn't find anything wrong in the installation logs you attached, but this might be something internal to VS package installation process that I can't relate to my plugin. 

Might I suggest some more troubleshooting by running below in VS2022 Developer Command Shell?
```
devenv.exe /clearcache
devenv /updateconfiguration
```
I also found others running into similar errors with Microsoft.VisualStudio.Composition as you are running into with the RoslynPackage. And the most common fix is to clear the ComponentModelCache here:

`%localappdata%\Microsoft\VisualStudio\17_xxxx\ComponentModelCache`

PS. I installed VS 2022 Enterprise edition myself (not the preview, but the final release). I then installed from the latest released version I created [here](https://github.com/sajalverma17/GitBranchDiffer/releases/tag/v1.0.8) and found no issues with all the three editions of VS I have added support for VS2022 (Pro, Community, Enterprise).

**Comment by sajalverma17** [comment]
While VS2022's latest update (v17.2) will come with a Git Branch Comparison, I still released support for VS2022 since I already added that. ¯\_(ツ)_/¯

Page for VS2022 version of the extension: https://marketplace.visualstudio.com/items?itemName=SajalVerma.GitBranchDifferDev17
